### ISSUE TITLE
Refactor Pread/Gread to use Index generics

### ISSUE THREAD

**Issue by m4b** [m4b/scroll#10]
1. This will have the effect of making the traits completely generic without need for impls
2. I believe this will allow TryFromCtx to remove offsetting logic
3. I believe this will allow complete library side implementations. E.g., as long as the bounds are satisfied, one could define custom structures to Pread out of !

**Comment by goandylok** [comment]
I suggest using [`num`](https://crates.io/search?q=num) crate to generic numbers, instead of this kind of code:
```rust
I: AddAssign + Copy + Add + Default + Debug,
```

**Comment by goandylok** [comment]
If we give up generic on buffer type (`[u8]`, the `This` type), and hard code it as [u8], we will be able to have fun with slices. 😆 That means all the offset will become the start position of slice, and the size will be slice's length.

No one will use things except [u8] as buffer, I think.

**Comment by m4b** [comment]
Done in #12
