### ISSUE TITLE
Examples of using #[derive(Pread, Pwrite)]

### ISSUE THREAD

**Issue by luser** [m4b/scroll#25]
The example in the README on [the scroll_derive repo](https://github.com/m4b/scroll_derive) doesn't work out of the box, and there aren't any docs on using derive in the scroll repo. It would be nice if there was an example to crib from somewhere!

**Comment by m4b** [comment]
I know I’m sorry 😐 need to do this; was going to do this when I reexported the derive crate a la failure style, but been so busy.

**Comment by m4b** [comment]
The best place for example is in scroll_derive tests which have derives + usage

**Comment by m4b** [comment]
@luser I think you fixed this? Reopen if not, and thanks again for your contributions!
