### ISSUE TITLE
[Feature Request] Wrapper types for providing a kind of Type-level (de)serialization context

### ISSUE THREAD

**Issue by kitlith** [m4b/scroll#33]
When you're trying to parse a file format filled with strings and other data with a specific endian, it may be convenient if you were able to derive the implementation for a struct
```rust
#[derive(Pread)]
struct Example<'a> {
    // reads a bigendian u16
    important: EndianWrapper<u16, byteorder::BE>,
    // reads a u8 length field and then reads out a string from the following bytes
    some_string: LengthData<&'a str, u8>
}
```

instead of having to manually implement TryFromCtx/TryIntoCtx like so:

```rust
struct Example<'a> {
    important: u16,
    some_string: &'a str
}

impl <'a> TryFromCtx<'a> for Example {
    type Error = scroll::Error;
    type Size = usize;
    fn try_from_ctx(src: &'a [u8], _ctx: ()) -> Result<(Self, Self::Size), Self::Error> {
        let important: u16 = src.pread_with(0, scroll::Endian::Big)?;
        let length: usize = src.pread::<u8>(2)?.into();
        let some_string: &'a str = src.pread_with(3, scroll::ctx::StrCtx::Length(length))?;
        Ok((Example { important, some_string }, 3 + some_string.len()))
    }
}
```
(Apologies if this doesn't actually work as-is, but you should get the idea.)

I bring this up because earlier today I created a couple of types intended for this purpose, including the `LengthData` type I mentioned above, if you're interested: https://gist.github.com/kitlith/feae830bfd48558e487a87becbd39ed1

`EndianWrapper` could probably be done similarly to the `UTF16` wrapper included in the gist, just operating on a single piece of data instead of a slice.

**Comment by m4b** [comment]
@kitlith Does https://docs.rs/scroll_derive not do what you want?

You should be able to do:

```rust
#[macro_use]
extern crate scroll;

#[derive(Pread)]
struct Foo {
  a: u64,
  b: u16,
}
```

And it should usually do what you want.

**NOTE**: to use `#[macro_use]` like above, must turn on the "derive" feature via your toml, something like:

```toml
[dependencies]
scroll = { features = ["derive"], version = "0.9" }
```

(i forget the exact syntax, but that's the gist)

**Comment by kitlith** [comment]
So, the idea is that this can be used *with* scroll_derive. How do you specify the context to that (say) Big Endian u64 and that Little Endian u16? How do you specify the context (which is a value passed to a function) at the "I'm just defining a struct and deriving" level?

**Comment by m4b** [comment]
Oh I think I understand. You want different endianness contexts for each field?

If yes, currently this must be done manually. It’s possible that the derive macro implementation could also receive annotation hints, similar to how serde or structopt annotates individual fields.

I’m not sure though; not a huge macro guru; would require some investigation. You are of course welcome to suggest ideas here or sketch out a possible PR :)

As long as it’s backwards compatible I’d be ok with adding something like:

#[ctx = Little]

On fields in a derived struct. I think this would only work with the endian enum? Not sure; it’s also probably some good amount of work for a potentially rare usecase ?

**Comment by kitlith** [comment]
I want to be able to provide context at compile-time where possible -- *this doesn't require modifying the derive macros*, it just requires using different types. If I had actually implemented an EndianWrapper type, I believe it would "just work" with the derive macro.

It also wouldn't be limited to just the Endian ctx, for example the "LengthData" type uses a template parameter to provide the data type that represents the length field -- so I can work with files that have a u16 length and files that have a u32 length... or both in the same file >_>. (yes, I have a file that uses UTF16 LE and BE and different sized length fields. ._.)

I guess I'm just providing an idea that I think would be really useful if it were expanded upon some more, because the only opportunity I've had to use the derive macro was on a file header that was used inside a TryFromCtx implementation to create a user-facing struct.

**Comment by kitlith** [comment]
That's why... I implemented the trait on a wrapper type that information tagged onto it using the templace system? Seriously, having a struct which contains a `LengthData<UTF16<byteorder::BE>, u16>` should already work with the code I've written in my gist that I linked in the OP. I'll try and write up an actual working test in a day or so.

**Comment by kitlith** [comment]
Here's a full example: https://github.com/kitlith/scroll-stuff

I'm replicating the (relatively small) usage without all of the type and trait impls here:
```rust
#[derive(Pread)]
struct Example {
    big: EndianWrapper<u16, BE>,
    little: EndianWrapper<u16, LE>,
    var: LengthData<UTF16<LE>, EndianWrapper<u16, BE>>
}

fn main() {
    let src = [0u8, 42, 42, 0, 0, 10, 0x48, 0, 0x65, 0, 0x6c, 0, 0x6c, 0, 0x6f, 0];
    let example: Example = src.pread(0).unwrap();
    let big: u16 = example.big.into();
    let little: u16 = example.little.into();
    let var: String = example.var.into();

    println!("Example {{ big: {}, little: {}, var: {} }}", big, little, var);

    assert_eq!(big, 42u16);
    assert_eq!(little, 42u16);
    assert_eq!(var, "Hello".to_owned());
}
```

Something that would make end usage nicer for the user would be a struct that removes all the wrapper types for easy usage, but my point stands that this is completely possible.

**Comment by m4b** [comment]
@kilith Um, wow; I’ve never seen scroll used like that before :P

So, if I understand correctly, you’d like to remove the two wrapper structs (at the very least) and their impls ? 

This would remove a lot of the boilerplate.

If yes, again, this looks like you want annotations on your derive, explicitly specifying the ctx for some (or all) fields, which should be possible.

However, I don’t see how it’s possible to remove the last wrapper, since that uses programmatic information to extract the String, iiuc? In which case we can’t do anything at derive/compile time.

Please correct me if I’m wrong and feel free to add anything else you have in mind. And thanks you so much for the example !

**Comment by kitlith** [comment]
Nah, I don't want to remove the wrapper structs. I want it to be easier to use scroll like this -- including some types like this in scroll.

**Comment by kitlith** [comment]
1. "types like this" -> `EndianWrapper`, maybe `LengthData`. I don't have a full list of stuff that might be useful, because I've just started looking at this stuff.
2. To the end user, it'd look roughly like what I copied out of my example. scroll would hold the implementations of `EndianWrapper` and such.
3. The user no longer has to implement TryFromCtx/TryIntoCtx in situations that these wrapper types would cover. I can provide a manual implementation for the example above, to compare and contrast, if that would help?

Perhaps this is better suited for a Pull Request, except that I wanted to discuss if the idea of wrapper types that work like `EndianWrapper` being provided in scroll is appealing before starting a PR.

**Comment by m4b** [comment]
So reading back through this issue, not sure what the resolution was here, or what would be actionable; it sounds like maybe some scroll extensions with commonly used types/targets might be useful? Not sure; e.g., i've written code in the past where I had "wrapper types" which were totally generic but took care of e.g., decoding something like a length encoded list of types, or a length encoded list of key value pairs, (like an encoded hashmap so to speak). But all this could technically be done as a third party crate; going to close, feel free to reopen if have other ideas
