### ISSUE TITLE
Docs mention lost Gread and Gwrite traits

### ISSUE THREAD

**Issue by spl** [m4b/scroll#67]
It appears that the trait `Gread` was demoted to oblivion in  605455704d95aebb36f114bcd79d7533609775e9; however, various parts of the API documentation still mention it. Here are two examples:

https://github.com/m4b/scroll/blob/e94a84d374161ccd3b966e0684fb72de6471e8a8/src/lib.rs#L17-L21
https://github.com/m4b/scroll/blob/8a205d8e22465b494c1cf7a02d8fe1034f044df2/src/ctx.rs#L140

**Comment by spl** [comment]
It appears something similar has occurred with `Gwrite` at a7a2e112efdfd62c388a6df263bee3cc0cd92a2f:

https://github.com/m4b/scroll/blob/e94a84d374161ccd3b966e0684fb72de6471e8a8/src/lib.rs#L23

**Comment by m4b** [comment]
Hi @spl Nice find ! 

Should be sufficient to just rename references to Pread/Pwrite since that’s where the methods were moved to

Would you like to submit a PR? And if you see anything else in the docs that’s weird, feel free to add that in too!

**Comment by spl** [comment]
> Should be sufficient to just rename references to Pread/Pwrite since that’s where the methods were moved to

I think the docs might need a bit more work than that. Considering that the first one starts with “there are 3 traits,” I think you'll want to say something more about `Pread`/`Pwrite` now that `Gread`/`Gwrite` are no longer than.

> Would you like to submit a PR? And if you see anything else in the docs that’s weird, feel free to add that in too!

Unfortunately, I don't expect to be able to do that. I just happened upon this, and it would take me a while to figure out what things mean and what to say. Sorry!
