### ISSUE TITLE
Pwrite deriving fails with "unparseable tokens" with struct containing lifetimes?

### ISSUE THREAD

**Issue by RaitoBezarius** [m4b/scroll#83]
Consider this structure:
```rust
#[derive(Pwrite)]
pub struct SymbolTable<'a> {
    symbols: &'a [u8],
}
```
(extracted from Goblin codebase)

This induces `proc-macro derive produced unparseable tokens`, on rustc 1.68.1.

I don't know what happens here.

**Comment by m4b** [comment]
That’s not good :/ must be something wrong with the scroll pwrite derive macro…

**Comment by Frostie314159** [comment]
I'm currently working on fixing that and cleaning up some of the derive code.

**Comment by m4b** [comment]
Would love if we got this fixed, @Frostie314159 did you manage to take a look at this? (I know you were working on other things, and thank you, just doing triage here)

**Comment by Frostie314159** [comment]
Yeah, I looked at the macro code and it's all a bit confusing, I couldn't work on this since I was busy with the 37c3, but maybe I can get back to this soon.

**Comment by m4b** [comment]
sounds good no rush, and if you don't feel like working on it, that's ok too :) anyway 0.12 scroll is out

**Comment by Frostie314159** [comment]
That's good to hear, btw happy new year from germany.
